### ISSUE TITLE
swaggerize-hapi is renamed to hapi-openapi

### ISSUE THREAD

**Issue by McFizh** [krakenjs/generator-swaggerize#109]
Link on the frontpage (swaggerized-hapi) redirects to a new github project called (hapi-openapi) .. 

You might want to update links on README.md and hapi generator.

**Comment by tlivings** [comment]
Addressed in `4.1.0`.

**Comment by McFizh** [comment]
There's still one more reference to old project in the middle of readme.md file:
swaggerize-hapi handlers

**Comment by tlivings** [comment]
😑
