### ISSUE TITLE
Pass the swagger source file as a CLI option

### ISSUE THREAD

**Issue by MattiSG** [krakenjs/generator-swaggerize#17]
It would be great if I was able to pass the generator an option for the input swagger document, so I can add an NPM script to update in a single command.

Example:

```json
…
"scripts": {
    "update-swagger": "yo swaggerize --framework=hapi --only=handlers,models --swaggerFile=swagger.json"
}
…
```

_Note_: the `--framework=hapi` option is linked to #16.

**Comment by kaasdude** [comment]
It would also be nice to have an extra parameter in the CLI and be able to point to an relative output where the handlers themselves will be generated, and also, prevent the generator in creating the handler folder itself.

**Comment by subeeshcbabu** [comment]
Please check the latest version `generator-swaggerize@3.0.0`. This should be resolved.
CLI Options : https://github.com/krakenjs/generator-swaggerize#cli-options

`--apiPath` - specify the path to the swagger document.
`--handlerPath` - specify the path to generate the handler files. By default handlers directory.
