### ISSUE TITLE
Path bug on Windows

### ISSUE THREAD

**Issue by jscti** [krakenjs/generator-swaggerize#40]
Hi

As pointed out here : https://github.com/krakenjs/swaggerize-express/issues/66 there is an issue on Windows while using this generator.

Bug occurs in server.js and tests files

**Comment by giowe** [comment]
same bug reported, all "\" chars are written with the escape char --> "/" in Window

![image](https://cloud.githubusercontent.com/assets/11004930/12103057/99633cb0-b33f-11e5-9b57-8e5de8d484ca.png)

**Comment by giowe** [comment]
I fixed the problem in this pull request https://github.com/krakenjs/generator-swaggerize/pull/56

**Comment by subeeshcbabu** [comment]
Is this really required for node version 4+ also?

**Comment by subeeshcbabu** [comment]
Please check the latest version `generator-swaggerize@3.0.0`. This should be resolved.
