### ISSUE TITLE
Support to define Reference Object as a Relative Schema File  

### ISSUE THREAD

**Issue by subeeshcbabu** [krakenjs/generator-swaggerize#61]
It would be nice to support definition of Reference object - `$ref` as a relative file to the main api definition file.
Swagger support - http://swagger.io/specification/#referenceObject 

For example:

```
{
  "$ref": "Pet.json"
}
```
```
$ref: 'Pet.yaml'
```

```
{
  "$ref": "definitions.json#/Pet"
}
```
```
$ref: 'definitions.yaml#/Pet'
```

**Comment by tlivings** [comment]
This can be done through `extrefs` integration into `swaggerize-routes`: https://github.com/tlivings/extrefs

**Comment by subeeshcbabu** [comment]
`generator-swaggerize@3.0.0` added support for `$ref`.
