### ISSUE TITLE
Fail yo swaggerize on windows 

### ISSUE THREAD

**Issue by lahiruk** [krakenjs/generator-swaggerize#89]
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "E:\\nodejs\\node.exe" "E:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! file F:\workspace\actorservice\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token 's' at 35:104
npm ERR! ze --only=handlers,models,tests --framework express --apiPath config\swagger.ya
npm ERR!                                                                      ^
npm ERR! File: F:\workspace\actorservice\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     F:\workspace\actorservice\npm-debug.log

change \ to / in package.json

**Comment by subeeshcbabu** [comment]
The generator has open issues on `windows` platform. @lahiruk Can you try the upcoming release alpha version `@3.0.0-alpha.5` ? Fixed most of the open issue as part of this major release. will be releasing the `rc` and stable version of 3.0.0 soon.

**Comment by lahiruk** [comment]
sure thanks. Thanks

**Comment by subeeshcbabu** [comment]
Please check the latest version `generator-swaggerize@3.0.0`. This should be resolved.
