### ISSUE TITLE
update the eslint config of the generated app

### ISSUE THREAD

**Issue by gaboesquivel** [krakenjs/generator-swaggerize#98]
@subeeshcbabu I've found this generator very useful, it would be nice to implement a different eslint config tho, I like both Standard and Airbnb.  Currently there are details like capitalized variable names ( I've seen that a lot in the hapi community ) that feels weird, I'm used to capitalized only classes and constructors.

**Comment by tlivings** [comment]
Hapi generates in a hapi style and express does not. You're always welcome to change the eslint config after the fact.

**Comment by gaboesquivel** [comment]
got it, yeah that's what I had to do in the project I'm working on,  that's was a lot work tho.  
That variable naming Hapi convention is really odd. I rather `const joi = require('joi)`
